server:
  port: 9192

spring:
  datasource:
    username: root
    password: Venkat@1995
    url: jdbc:mysql://localhost:3306/soft
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
      format_sql: true
